version: 2

jobs:
  Adidas Client:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: cd client && npm ci
      - run: cd client && npm test

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd client && npx apollo client:push
          fi

  Adidas Server:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: cd server && npm install
      - run: cd server && npm ci
      - run: cd server && npm test

      - run:
          name: Starting server
          command: cd server && npm run start:ci
          background: true

      - run: sleep 5
      - run: cd server && npx apollo service:check

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd server && npx apollo service:push
          fi

workflows:
  version: 2
  Build and Test:
    jobs:
      - Adidas Client
      - Adidas Server
